include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-ytunblock
PKG_RELEASE:=1

LUCI_TITLE:=YT Unblock — LuCI
LUCI_DEPENDS:=+luci-base +ytunblock
LUCI_PKGARCH:=all
LUCI_LANGUAGES:=en ru

PKG_LICENSE:=GPL-3.0-or-later
PKG_MAINTAINER:=ytunblock-owrt

include ./luci.mk

# call BuildPackage - OpenWrt buildroot signature
